apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ .Values.noobaa_name }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  cleanupPolicy:
    {{- toYaml .Values.noobaa_cleanuppolicy | nindent 4 }}
  coreResources:
    {{- toYaml .Values.noobaa_coreresources | nindent 4 }}
  dbResources:
    {{- toYaml .Values.noobaa_dbresources | nindent 4 }}
{{- if .Values.noobaa_dbstorageclass }}
  dbStorageClass: {{ .Values.noobaa_dbstorageclass }}
{{- end }}
  dbType: {{ .Values.noobaa_dbtype }}
{{- if .Values.noobaa_dbvolumeresources }}
  dbVolumeResources:
    {{- toYaml .Values.noobaa_dbvolumeresources | nindent 4 }}
{{- end }}
  loadBalancerSourceSubnets: {}
  security:
    kms: {}
