apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
    {{- include "common.labels.labels" . | nindent 4 }}
  name: noobaa-pv-backing-store
  namespace: {{ template "common.names.namespace" $ }}
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 50Gi
  type: pv-pool
