apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: resource-locker-noobaa-rolebinding
  namespace: {{ template "common.names.namespace" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: resource-locker-noobaa-role
subjects:
  - kind: ServiceAccount
    name: resource-locker-noobaa-sa
    namespace: openshift-storage
