apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: resource-locker-noobaa-role
  namespace: {{ template "common.names.namespace" $ }}
rules:
  - apiGroups:
      - noobaa.io
    resources:
      - bucketclasses
    verbs:
      - create
      - patch
      - list
      - update
      - get
