apiVersion: v1
kind: Service
metadata:
  labels:
    vm.kubevirt.io/name: image-builder
  name: image-builder
  namespace: rfe
spec:
  ports:
  - name: 22-tcp
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.kubevirt.io/name: image-builder
  sessionAffinity: None
  type: ClusterIP
