apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    run: image-builder-vm-ansible-job
  name: image-builder-vm-ansible-job
  namespace: rfe
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
          env:
            - name: GIT_DIRECTORY
              value: "/tmp/git/rhel-edge-automation-arch"
            - name: GIT_URL
              value: "https://github.com/redhat-cop/rhel-edge-automation-arch.git"
            - name: SSH_KEY
              value: "/var/secrets/image-builder-ssh-key/ssh-privatekey"
            - name: ANSIBLE_PLAYBOOK
              value: "ansible/playbooks/configure-image-builder.yaml"
            - name: ANSIBLE_CONFIG
              value: $GIT_DIRECTORY/ansible/ansible.cfg
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p $GIT_DIRECTORY
              git clone $GIT_URL $GIT_DIRECTORY
              ansible-galaxy collection install -r $GIT_DIRECTORY/ansible/collections/requirements.yaml
              ansible-playbook -u cloud-user --private-key=$SSH_KEY $GIT_DIRECTORY/$ANSIBLE_PLAYBOOK
          volumeMounts:
            - name: image-builder-ssh-key
              mountPath: /var/secrets/image-builder-ssh-key
              readOnly: yes
            - name: redhat-portal-credentials
              mountPath: /var/secrets/redhat-portal-credentials
              readOnly: yes
          imagePullPolicy: Always
          name: ansible-rfe-runner
      volumes:
        - name: image-builder-ssh-key
          secret:
            secretName: image-builder-ssh-key
            defaultMode: 0400
        - name: redhat-portal-credentials
          secret:
            secretName: redhat-portal-credentials
            defaultMode: 0400
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: rfe-automation
      serviceAccountName: rfe-automation
      terminationGracePeriodSeconds: 30