apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-machineset-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift/gitops/clusters/overlays/shared/argocd/configs
    repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
