apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.quayRegistryCR.annotations | nindent 4 }}
spec:
  components:
{{- range .Values.quay.components }}
    - kind: {{ .kind }}
      managed: {{ .managed }}
{{- end }}
