apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ .Values.serviceAccount }}-quay
  namespace: {{ .Values.quayRegistryCR.targetNamespace }}
  annotations:
    {{- toYaml .Values.setupJob.annotations | nindent 4 }}  
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - quay.redhat.com
    resources:
      - quayregistries
    verbs:
      - get
      - list
