apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-resource-locker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift/gitops/manifests/configs/resource-locker/base
    repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 20m
      limit: 30
