apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - noobaa.yaml
  - noobaa-pv-backing-store.yaml
