apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - namespace.yaml
  - noobaa-pv-backing-store.yaml
  - noobaa.yaml
  - operatorgroup.yaml
  - resource-locker-noobaa-patch.yaml
  - resource-locker-noobaa-rolebinding.yaml
  - resource-locker-noobaa-role.yaml
  - resource-locker-noobaa-sa.yaml
  - subscription.yaml
