apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-locker-noobaa-role
  namespace: openshift-storage
rules:
  - apiGroups:
      - noobaa.io
    resources:
      - bucketclasses
    verbs:
      - create
      - patch
      - list
      - update
      - get
