apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-locker-noobaa-rolebinding
  namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: resource-locker-noobaa-role
subjects:
  - kind: ServiceAccount
    name: resource-locker-noobaa-sa
    namespace: openshift-storage
