apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rfe-oauth
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}  
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - oauths
    verbs:
      - get
      - patch
