apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: {{ template "common.names.namespace" $ }}
  annotations:
    {{- toYaml .Values.kubevirtCR.annotations | nindent 4 }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    {{- toYaml .Values.kubevirtCR.labels | nindent 4 }}
spec:
  infra: {}
  workloads: {}
