apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kubevirt-hyperconverged-group
  namespace: {{ template "common.names.namespace" $ }}
spec:
  targetNamespaces:
    - {{ .Values.namespace }}