apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation
  namespace: rfe
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - "*"
    resources:
      - pods
      - services
    verbs:
      - list
      - get
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - update
      - create
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
    verbs:
      - get
      - list
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
