apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation
  namespace: rfe
rules:
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - "*"
    resources:
      - secrets
      - services
      - configmaps
      - deployments
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - update
      - create
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
    verbs:
      - get
      - list
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - machine.openshift.io
    resources:
      - machinesets
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
