apiVersion: v2
name: user-workload-monitoring
description: User Workload Monitoring Helm Chart
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
