apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-machineset-infrastructures
  namespace: rfe
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
