apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-machineset-machinesets
  namespace: openshift-machine-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-machineset-machinesets
subjects:
  - kind: ServiceAccount
    name: aws-machineset
    namespace: rfe
