iso_fetch_path: http://httpd:8080/images

iso_source_name: rhel-8.3-x86_64-boot.iso
iso_source_path: /tmp

iso_mount_base_path: /tmp/boot-iso

# Default name. Can override by passing
# -e "edge_iso_name=<name>" to ansible-playbook command.
edge_iso_name: rfe-8.3-x86_64-auto-kickstart.iso
edge_iso_path: /tmp
edge_iso_remote_path: /var/www/html/images

scratch_base_path: /tmp/boot-iso-scratch

# Default hello-world kickstart. Can override by passing
# -e "kickstart_url=<url>" to ansible-playbook command.
kickstart_url: http://httpd:8080/kickstarts/hello-world/kickstart.ks

# Override with -e iso_storage_url=$(results.iso-storage-url.path)
iso_storage_url: /tmp/iso-storage-url