apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonCR.annotations | nindent 4 }}    
  name: rfe-oci-build-image
spec:
  workspaces:
    - name: workspace
  params:
    - name: blueprint-dir
      description: Directory Contaning blueprint.toml File
      type: string
    - name: image-builder-secret
      description: Name of the secret containing the SSH key for the image builder
      default: "image-builder-ssh-key"
      type: string
  results:
    - name: build-commit
      description: Commit ID of the Build
    - name: image-builder-host
      description: Image Builder Host used for Pipeline Run
  steps:
    - name: build-image-playbook
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook \
            -u cloud-user \
            --private-key=/var/secrets/image-builder-ssh/ssh-privatekey \
            -e blueprint_source_dir=$(params.blueprint-dir) \
            -e build_commit_output_file=$(results.build-commit.path) \
            -e image_builder_host_output_file=$(results.image-builder-host.path) \
            playbooks/oci-create-image.yaml
      command:
        - /bin/bash
        - -c
      volumeMounts:
        - name: publisher
          mountPath: /var/secrets/publisher
          readOnly: true
        - name: quay-rfe-setup
          mountPath: /var/secrets/quay-rfe-setup
          readOnly: true
        - name: image-builder-ssh
          mountPath: /var/secrets/image-builder-ssh
          readOnly: true
  volumes:
    - name: publisher
      secret:
        defaultMode: 0440
        secretName: publisher
    - name: quay-rfe-setup
      secret:
        defaultMode: 0440
        secretName: quay-rfe-setup
    - name: image-builder-ssh
      secret:
        defaultMode: 0440
        secretName: "$(params.image-builder-secret)"
