apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonCR.annotations | nindent 4 }}
  name: rfe-oci-publish-content
spec:
  workspaces:
    - name: workspace
  params:
    - name: image-path
      description: Path to RFE Container Image
    - name: image-tag
      description: Tag Associated with the RFE Image to Deploy
    - name: skip-free-space-protection
      description: Instruct OSTree to skip its free space protection
  results:
    - name: content-path
      description: URL to OSTree Content
  steps:
    - name: publish-content-playbook
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook \
            -e quay_image_path=$(params.image-path) \
            -e quay_image_tag=$(params.image-tag) \
            -e skip_free_space_protection=$(params.skip-free-space-protection) \
            -e content_path_output_file=$(results.content-path.path) \
            playbooks/oci-publish-content.yaml
      command:
        - /bin/bash
        - -c
