apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonCR.annotations | nindent 4 }}    
  name: rfe-oci-iso-pipeline
spec:
  params:
    - name: tooling-git-url
      description: Tooling Repository URL
      default: {{ $.Values.pipelines.repos.tooling.repoURL }}
      type: string
    - name: tooling-git-revision
      description: Tooling Repository URL Reference
      default: {{ $.Values.pipelines.repos.tooling.targetRevision }}
      type: string
    - name: blueprint-dir
      description: Directory in Blueprints repository containing blueprint
      default: rfe-iso-blueprint
      type: string
    - name: blueprints-git-url
      description: Blueprint Repository URL
      default: {{ $.Values.pipelines.repos.blueprints.repoURL }}
      type: string
    - name: blueprints-git-revision
      description: Blueprints Repository URL Reference
      default: {{ $.Values.pipelines.repos.blueprints.targetRevision }}
      type: string
    - name: kickstart-url
      description: URL Pointing to Kickstart Location
      type: string
    - name: ostree-repo-url
      description: URL Containing the OSTree Content
      type: string
    - name: image-builder-secret
      description: Name of the Secret Containing the SSH Key for the Image Builder Host
      default: "image-builder-ssh-key"
      type: string
    - name: iso-blueprint
      description: Name of the Blueprint to use for the ISO Build (Should not be Customized)
      default: "rfe-iso-blueprint"
      type: string
    - name: additional-content-sources
      description: JSON object with list of Additional Image Builder sources
      default: {{ $.Values.pipelines.additional_content_sources | toJson | b64enc }}
      type: string
    - name: rhsm-repositories
      description: JSON object with list of RHEL Repos
      default: {{ $.Values.pipelines.rhsm_repositories | toJson | b64enc }}
      type: string
  results:
    - name: build-commit-id
      description: Commit ID of the Build
      value: $(tasks.rfe-oci-build-installer-image.results.build-commit-id)
    - name: image-builder-host
      description: Image Builder Host used for Pipeline Run
      value: $(tasks.rfe-oci-build-installer-image.results.image-builder-host)
    - name: iso-url
      description: URL containing Autobooting Image
      value: $(tasks.rfe-oci-build-auto-iso.results.iso-url)
  workspaces:
    - name: shared-workspace
  tasks:
    - name: git-clone-tooling
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.tooling-git-url)
        - name: revision
          value: $(params.tooling-git-revision)
        - name: subdirectory
          value: "tooling"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: git-clone-blueprints
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.blueprints-git-url)
        - name: revision
          value: $(params.blueprints-git-revision)
        - name: subdirectory
          value: "blueprints"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: rfe-oci-build-installer-image
      taskRef:
        name: rfe-oci-build-installer-image
        kind: Task
      params:
        - name: ostree-repo-url
          value: $(params.ostree-repo-url)
        - name: image-builder-secret
          value: $(params.image-builder-secret)
        - name: iso-blueprint
          value: /workspace/workspace/blueprints/$(params.iso-blueprint)
        - name: additional-content-sources
          value: $(params.additional-content-sources)
        - name: rhsm-repositories
          value: $(params.rhsm-repositories)
      runAfter:
        - "git-clone-tooling"
        - "git-clone-blueprints"
      workspaces:
        - name: workspace
          workspace: shared-workspace
    - name: rfe-oci-build-auto-iso
      taskRef:
        name: rfe-oci-build-auto-iso
        kind: Task
      params:
        - name: build-commit-id
          value: $(tasks.rfe-oci-build-installer-image.results.build-commit-id)
        - name: image-builder-host
          value: $(tasks.rfe-oci-build-installer-image.results.image-builder-host)
        - name: image-builder-secret
          value: $(params.image-builder-secret)
        - name: kickstart-url
          value: $(params.kickstart-url)
      runAfter:
        - "rfe-oci-build-installer-image"
      workspaces:
        - name: workspace
          workspace: shared-workspace
