apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonCR.annotations | nindent 4 }}    
  name: rfe-oci-build-installer-image
spec:
  workspaces:
    - name: workspace
  params:
    - name: ostree-repo-url
      description: URL Containing the OSTree Content
      type: string
    - name: image-builder-secret
      description: Name of the Secret Containing the SSH Key for the Image Builder Host
      default: "image-builder-ssh-key"
      type: string
    - name: iso-blueprint
      description: Name of the Blueprint to use for the ISO Build (Should not be Customized)
      default: "rfe-iso-blueprint"
      type: string
    - name: additional-content-sources
      description: JSON object with list of Additional Image Builder sources
      type: string
    - name: rhsm-repositories
      description: JSON object with list of RHEL Repos
      type: string
  results:
    - name: build-commit-id
      description: Commit ID of the Build
    - name: image-builder-host
      description: Image Builder Host used for Pipeline Run
  steps:
    - name: build-installer-image-playbook
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook \
            -u cloud-user \
            --private-key=/var/secrets/image-builder-ssh/ssh-privatekey \
            -e blueprint_source_dir=$(params.iso-blueprint) \
            -e ostree_repo_url=$(params.ostree-repo-url) \
            -e build_commit_id_output_file=$(results.build-commit-id.path) \
            -e image_builder_host_output_file=$(results.image-builder-host.path) \
            -e additional_content_sources=$(params.additional-content-sources) \
            -e rhsm_repositories=$(params.rhsm-repositories) \
            playbooks/oci-build-installer-image.yaml
      command:
        - /bin/bash
        - -c
      volumeMounts:
        - name: image-builder-ssh
          mountPath: /var/secrets/image-builder-ssh
          readOnly: true
  volumes:
    - name: image-builder-ssh
      secret:
        defaultMode: 0440
        secretName: "$(params.image-builder-secret)"
