apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: patch-operator-{{ template "common.names.fullname" . }}
rules:
  - verbs:
      - create
      - update
      - patch
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - noobaa.io
    resources:
      - noobaas