apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterMonitoringConfig.name }}
  namespace: {{ .Values.clusterMonitoringConfig.namespace }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
data:
  config.yaml: |
    enableUserWorkload: true
