apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.userWorkloadMonitoringConfig.name }}
  namespace: {{ .Values.userWorkloadMonitoringConfig.namespace }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
data:
  config.yaml: |
