apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-machineset-infrastructures
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-machineset-infrastructures
subjects:
- kind: ServiceAccount
  name: aws-machineset
  namespace: {{ template "common.names.namespace" $ }}