apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-machineset-machinesets
  namespace: openshift-machine-api
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - machine.openshift.io
    resources:
      - machinesets
    verbs:
      - create
      - patch
      - list
      - update
      - get
