apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-machineset-infrastructures
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
