apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oci-rfe-httpd-role
  namespace: {{ .Values.project_namespace }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - anyuid
