apiVersion: v1
imagePullSecrets:
- name: publisher
kind: ServiceAccount
metadata:
  name: oci-rfe-httpd
  namespace: {{ .Values.project_namespace }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
