apiVersion: v1
imagePullSecrets:
- name: publisher
kind: ServiceAccount
metadata:
  name: oci-rfe-httpd
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
