apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation-ingress-secrets
  namespace: openshift-ingress
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - get
      - list
