apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rfe-automation-proxy
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - proxies
    verbs:
      - list
      - get
