apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreamimports
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - "*"
    resources:
      - secrets
      - services
      - configmaps
      - deployments
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - update
      - create
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstance
      - virtualmachineinstances
    verbs:
      - get
      - list
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - pipelines-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
