apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation-openshift-config
  namespace: openshift-config
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - v1
    resources:
      - configmaps
    verbs:
      - get
      - list
