{{- if .Values.operatorgroup.create }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ template "common.names.fullname" . }}
  generateName: {{ template "common.names.fullname" . }}-
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  {{- if .Values.operatorgroup.annotations }}
  annotations:
    {{- toYaml .Values.operatorgroup.annotations | nindent 4 }}
  {{- end }}
spec:
  targetNamespaces:
    - {{ template "common.names.namespace" . }}
{{- end }}