apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rfe

resources:
  - build-rfe-task.yaml
  - download-upload-rfe-task.yaml
  - rfe-kickstart-pipeline.yaml
  - rfe-tarball-pipeline.yaml
  - upload-kickstart-task.yaml
  - rfe-oci-build-image-task.yaml
  - rfe-oci-image-pipeline.yaml
  - rfe-oci-push-image-task.yaml
  - rfe-oci-quay-repository-task.yaml
