apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: rfe-oci-build-installer-image
spec:
  workspaces:
    - name: workspace
  params:
    - name: ostree-repo-url
      description: URL Containing the OSTree Content
      type: string
    - name: image-builder-secret
      description: Name of the Secret Containing the SSH Key for the Image Builder Host
      default: "image-builder-ssh-key"
      type: string
    - name: iso-blueprint
      description: Name of the Blueprint to use for the ISO Build (Should not be Customized)
      default: "rfe-iso-blueprint"
      type: string
  results:
    - name: build-commit-id
      description: Commit ID of the Build
  steps:
    - name: build-installer-image-playbook
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook \
            -u cloud-user \
            --private-key=/var/secrets/image-builder-ssh/ssh-privatekey \
            -e blueprint_source_dir=$(params.iso-blueprint) \
            -e ostree_repo_url=$(params.ostree-repo-url) \
            -e build_commit_id_output_file=$(results.build-commit-id.path) \
            playbooks/oci-build-installer-image.yaml
      command:
        - /bin/bash
        - -c
      volumeMounts:
        - name: image-builder-ssh
          mountPath: /var/secrets/image-builder-ssh
          readOnly: true
  volumes:
    - name: image-builder-ssh
      secret:
        defaultMode: 0440
        secretName: "$(params.image-builder-secret)"
