storage:
  odf:
    enabled: true
    namespace: openshift-storage
    storageClassName: openshift-storage.noobaa.io
    bucketClass: noobaa-default-bucket-class
  s3:
    enabled: true
    secret: ""
  file:
    accessMode: ReadWriteMany
    size: 20Gi

ingress:
  termination: Edge
  type: route
  loadbalancerPort: 80
image:
  tag: stable
  image: quay.io/pulp/pulp
  pullPolicy: IfNotPresent

resourceManager:
  replicas: 1

web:
  replicas: 1
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

content:
  replicas: 1
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

worker:
  replicas: 2
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

settings:
  AWS_S3_VERIFY: false
  TOKEN_AUTH_DISABLED: true

commonCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
