apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rfe

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - route.yaml
  - httpd-ostree-imagestream.yaml
  - httpd-ostree-buildconfig.yaml