kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
spec:
  runPolicy: Serial
  source:
    type: Dockerfile
    dockerfile: |
      FROM {{ template "common.images.registryRepository" .Values.ansible_rfe_runner.image }}
      USER 0
      RUN dnf install skopeo -y && \
          pip install --upgrade pip && \
          pip install openshift && \
          pip install jmespath && \
          pip install netaddr && \
          pip install ansible==2.9.* && \
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
            tar -xvzf - -C /usr/local/bin/ oc && chmod 755 /usr/local/bin/oc && ln -s /usr/local/bin/oc /usr/local/bin/kubectl
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: {{ template "common.images.image" .Values.ansible_rfe_runner.image }}
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "common.names.fullname" . }}:latest
