{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
{{- if or (.description) (.displayname) }}
  annotations:
{{- end }}
{{- if .description }}
    openshift.io/description: {{ .description | quote }}
{{- end }}
{{- if .displayname }}
    openshift.io/display-name: {{ .displayname | quote }}
{{- end }}
  name: {{ .name }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
{{- if .monitoring }}
    openshift.io/cluster-monitoring: "true"
{{- end }}
{{- end }}
