- name: Generate In-Memory Inventory of OpenShift VMs
  gather_facts: no
  hosts: localhost
  roles:
    - role: openshift-image-builder-imi

- name: Find Appropriate Image Builder Host
  become: yes
  hosts: builders
  roles:
    - role: pipeline-scheduler

- name: Create OCI Image
  become: yes
  gather_facts: no
  hosts: pipeline_target_host
  tasks:
    - name: Configure Content Sources
      ansible.builtin.include_role:
        name: image-builder-content-sources

    - name: Build OCI Image
      ansible.builtin.include_role:
        name: oci-build-image
