- name: Generate In-Memory Inventory of OpenShift VMs
  gather_facts: false
  hosts: localhost
  roles:
    - role: openshift-image-builder-imi
      vars:
        pipeline_mode: true

- name: Find Appropriate Image Builder Host
  become: true
  hosts: builders
  roles:
    - role: pipeline-scheduler

- name: Create OCI Image
  become: true
  gather_facts: false
  hosts: pipeline_target_host
  tasks:
    - name: Configure Content Sources
      ansible.builtin.include_role:
        name: image-builder-content-sources

    - name: Build OCI Image
      ansible.builtin.include_role:
        name: oci-build-image
