- name: Generate In-Memory Inventory of OpenShift VMs
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Assert image_builder_host is Defined
      ansible.builtin.assert:
        that:
          - image_builder_host is defined

    - name: Add Target Host to Inventory
      ansible.builtin.add_host:
        ansible_ssh_host: "{{ image_builder_host }}"
        ansible_ssh_port: "22"
        name: pipeline_target_host
      delegate_to: localhost

- name: Push OCI Image
  become: yes
  gather_facts: no
  hosts: pipeline_target_host
  tasks:
    - name: Push OCI Image
      include_role:
        name: oci-push-image
