---
quay:
  components:
    - kind: clair
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: objectstorage
      managed: true
    - kind: postgres
      managed: true
    - kind: redis
      managed: true
    - kind: route
      managed: true

subscription:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed


quayRegistryCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

setupJob:
  gitRepository: https://github.com/redhat-cop/rhel-edge-automation-arch.git
  gitBranch: main
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
  namespace: rfe