apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rfe-rbac
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: rfe
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
      kind: ServiceAccount
      name: oci-rfe-httpd
      namespace: rfe
  project: rfe
  source:
    path: openshift/gitops/manifests/rfe/rbac/base
    repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 20m
      limit: 30
