- name: Deploy Sealed Secrets for Kubernetes
  k8s:
    api_key: "{{ openshift_ansible_sa_token }}"
    definition: "{{ lookup('template', 'templates/sealed-secrets.j2') }}"
    host: "{{ openshift_api }}"
    state: present
    username: "{{ openshift_ansible_sa }}"
    validate_certs: no
  tags:
    - sealed-secrets