apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../manifests/configs/cnv/base

resources:
  - image-builder-ssh-key-sealed-secret.yaml
  - redhat-portal-credentials-sealed-secret.yaml 
