{{- $setupJobName := include "common.names.appendSuffix" (dict "suffix" "setup" "context" $) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $setupJobName }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.setupJob.annotations | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $setupJobName }}
subjects:
  - kind: ServiceAccount
    name: {{ $setupJobName }}
    namespace: {{ template "common.names.namespace" $ }}
