apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ .Values.nexus.service }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: nexus
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: docker
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP
