apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ .Values.nexus.route }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.nexus.service }}
    weight: 100
  wildcardPolicy: None
