apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.buildConfig.output.imageStreamTagName }}","namespace":"{{- template "common.names.namespace" $ }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"httpd\")].image"}]'
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpd
  strategy: {}
  template:
    metadata:
      labels:
        deployment: httpd
    spec:
      containers:
        - image: " "
          name: httpd
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/www/html
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: httpd
