kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.buildConfig.name }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.buildConfig.output.imageStreamTagName }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM registry.redhat.io/rhel8/httpd-24
      USER 0
      COPY ./etc-pki-entitlement /etc/pki/entitlement
      COPY ./rhsm-conf /etc/rhsm
      COPY ./rhsm-ca /etc/rhsm/ca
      RUN rm /etc/rhsm-host && \
        dnf repolist --disablerepo=* && \
        subscription-manager repos --disable=* && \
        {{ range .Values.buildConfig.enableRepositories }}subscription-manager repos --enable {{ . }} && {{ end }}\
        dnf update -y && \
        dnf install -y ostree && \
        rm -rf /etc/pki/entitlement && \
        rm -rf /etc/rhsm && \
        /usr/libexec/httpd-prepare && rpm-file-permissions
      USER 1001
    secrets:
    - destinationDir: etc-pki-entitlement
      secret:
        name: etc-pki-entitlement
    - destinationDir: rhsm-ca
      secret:
        name: rhsm-ca
    - destinationDir: rhsm-conf
      secret:
        name: rhsm-conf
    type: Dockerfile
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: {{ .Values.buildConfig.strategy.dockerStrategyFrom.name | quote }}
        namespace: openshift
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange