apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.buildConfig.name }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
spec: {}