apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ template "common.names.fullname" . }}
    weight: 100
