apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    deployment: {{ template "common.names.fullname" . }}
