---
config:
  env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: "rfe-gitops"

namespaces:
  - name: rfe-gitops
    annotations:
      openshift.io/description: RFE GitOps
      openshift.io/display-name: RFE GitOps

# OpenShift GitOps
operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

operatorgroup:
  create: false
