- name: Query VirtualMachineInstances
  community.kubernetes.k8s_info:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    api_version: kubevirt.io/v1alpha3
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: https://kubernetes.default.svc
    kind: VirtualMachineInstance
    namespace: rfe
    username: rfe-automation
    validate_certs: yes
  register: vmi_results

- name: Debug vmi_results
  ansible.builtin.debug:
    msg: "{{ item.spec.hostname }} - {{ item.status.interfaces[0].ipAddress }}"
    verbosity: 1
  loop: "{{ vmi_results.resources }}"

- name: Generate In-Memory Inventory of All VMs
  ansible.builtin.add_host:
    ansible_ssh_host: "{{ item.status.interfaces[0].ipAddress }}"
    ansible_ssh_port: "22"
    hostname: "{{ item.spec.hostname }}"
  loop: "{{ vmi_results.resources }}"