- name: Generate Access Token
  ansible.builtin.uri:
    body:
      client_id: rhsm-api
      grant_type: refresh_token
      refresh_token: "{{ lookup('file', '/var/secrets/redhat-portal-credentials/offline_token') }}"
    body_format: form-urlencoded
    method: POST
    url: "{{ redhat_sso_url }}"
  register: access_token

- name: Generate Image Download URLs
  ansible.builtin.uri:
    follow_redirects: none
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    status_code: 307
    url: "{{ redhat_api_url }}/images/{{ item }}/download"
  register: image_urls
  loop: "{{ image_checksums }}"

- name: Download Red Hat Images
  ansible.builtin.get_url:
    checksum: "sha256:{{ item.item }}"
    dest: "{{ initial_download_path }}/{{ item.json.body.filename }}"
    url: "{{ item.json.body.href }}"
  loop: "{{ image_urls.results }}"