# install to openshift-operators namespace
---
operator:
  channel: alpha
  installPlanApproval: Automatic
  name: resource-locker-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
operatorgroup:
  create: false
