apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- toYaml .Values.ansibleVM.annotations | nindent 4 }}
  labels:
    run: image-builder-vm-ansible-job
    {{- include "common.labels.labels" . | nindent 4 }}
  name: image-builder-vm-ansible-job
  namespace: rfe
spec:
  activeDeadlineSeconds: {{ $.Values.ansibleVM.activeDeadlineSeconds }}
  template:
    spec:
      activeDeadlineSeconds: {{ $.Values.ansibleVM.activeDeadlineSeconds }}
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
          env:
            - name: GIT_DIRECTORY
              value: "/tmp/git/rhel-edge-automation-arch"
            - name: GIT_URL
              value: {{ $.Values.gitRepository | quote }}
            - name: SSH_KEY
              value: "/var/secrets/image-builder-ssh-key/ssh-privatekey"
            - name: ANSIBLE_PLAYBOOK
              value: "ansible/playbooks/configure-image-builder.yaml"
            - name: ANSIBLE_CONFIG
              value: $GIT_DIRECTORY/ansible/ansible.cfg
            - name: GIT_BRANCH
              value: {{ $.Values.gitBranch | quote }}
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p $GIT_DIRECTORY
              git clone -b $GIT_BRANCH $GIT_URL $GIT_DIRECTORY
              ansible-galaxy collection install -r $GIT_DIRECTORY/ansible/collections/requirements.yaml
              ansible-playbook -vvvv -u cloud-user --private-key=$SSH_KEY $GIT_DIRECTORY/$ANSIBLE_PLAYBOOK
          volumeMounts:
            - name: image-builder-ssh-key
              mountPath: /var/secrets/image-builder-ssh-key
              readOnly: true
            - name: redhat-portal-credentials
              mountPath: /var/secrets/redhat-portal-credentials
              readOnly: true
            - name: composer-config
              mountPath: /var/configs/composer
              readOnly: true
          imagePullPolicy: Always
          name: ansible-rfe-runner
      volumes:
        - name: image-builder-ssh-key
          secret:
            secretName: image-builder-ssh-key
            defaultMode: 0400
        - name: redhat-portal-credentials
          secret:
            secretName: redhat-portal-credentials
            defaultMode: 0400
        - name: composer-config
          configMap:
            name: image-builder-vm-composer
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: rfe-automation
      serviceAccountName: rfe-automation
      terminationGracePeriodSeconds: 30 