- name: Query VirtualMachineInstances
  community.kubernetes.k8s_info:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    api_version: kubevirt.io/v1alpha3
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: https://kubernetes.default.svc
    kind: VirtualMachineInstance
    label_selectors:
      - app=image-builder
    namespace: rfe
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    validate_certs: yes
  delay: 10
  register: vmi_results
  retries: 60
  until:
    - vmi_results.resources | default([]) | list | count == instance_expected_count

- name: Generate In-Memory Inventory of Image Builder VM
  ansible.builtin.add_host:
    ansible_ssh_host: "{{ item.status.interfaces[0].ipAddress }}"
    ansible_ssh_port: "22"
    groups:
      - builders
    name: "{{ item.metadata.name }}"
  loop: "{{ vmi_results.resources }}"
