- name: Query VirtualMachineInstances
  community.kubernetes.k8s_info:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    api_version: kubevirt.io/v1alpha3
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: https://kubernetes.default.svc
    kind: VirtualMachineInstance
    namespace: rfe
    name: image-builder
    username: rfe-automation
    validate_certs: yes
  register: vmi_results
  retries: 60
  delay: 10
  until:
    - vmi_results.resources | default([]) | list | count == 1
    - vmi_results.resources | default([]) | list | first | json_query("status.interfaces[0].ipAddress") | ipaddr

- name: Debug vmi_results
  ansible.builtin.debug:
    msg: "image-builder - {{ vmi_results.resources[0].status.interfaces[0].ipAddress }}"
    verbosity: 1

- name: Generate In-Memory Inventory of Image Builder VM
  ansible.builtin.add_host:
    ansible_ssh_host: "{{ vmi_results.resources[0].status.interfaces[0].ipAddress }}"
    ansible_ssh_port: "22"
    hostname: image-builder