- name: Run in Pipeline Mode
  ansible.builtin.import_tasks:
    file: pipeline-mode.yaml
  when:
    - pipeline_mode | bool

- name: Run in Standard Mode
  ansible.builtin.import_tasks:
    file: standard-mode.yaml
  when:
    - not (pipeline_mode | bool)
